export const MENU_ITEMS = [
  {
    id: "1",
    name: "Hamburger",
    price: 18,
    category: "Main Course",
    description: "Juicy grilled beef patty with lettuce, tomato, and cheese",
  },
  {
    id: "2",
    name: "New York Steak",
    price: 42,
    category: "Main Course",
    description: "Grilled to perfection, served with garlic butter and herbs",
  },
  {
    id: "3",
    name: "Grilled Chicken",
    price: 27,
    category: "Main Course",
    description: "Marinated chicken breast grilled and served with veggies",
  },
  {
    id: "4",
    name: "BBQ Ribs",
    price: 36,
    category: "Main Course",
    description: "Slow-cooked ribs smothered in tangy barbecue sauce",
  },
  {
    id: "5",
    name: "Fish & Chips",
    price: 24,
    category: "Main Course",
    description: "Crispy battered fish served with golden fries and tartar sauce",
  },
  {
    id: "6",
    name: "Caesar Salad",
    price: 17,
    category: "Appetizers",
    description: "Crisp romaine lettuce with Caesar dressing, croutons, and Parmesan",
  },
  {
    id: "7",
    name: "Buffalo Wings",
    price: 15,
    category: "Appetizers",
    description: "Spicy chicken wings served with blue cheese dip",
  },
  {
    id: "8",
    name: "French Fries",
    price: 8,
    category: "Appetizers",
    description: "Crispy golden fries with a side of ketchup",
  },
  {
    id: "9",
    name: "Coca Cola",
    price: 5,
    category: "Beverages",
    description: "Refreshing cold Coca Cola",
  },
  {
    id: "10",
    name: "Iced Tea",
    price: 5,
    category: "Beverages",
    description: "Chilled iced tea with a hint of lemon",
  },
  {
    id: "11",
    name: "Coffee",
    price: 6,
    category: "Beverages",
    description: "Hot brewed coffee, served black or with cream and sugar",
  },
  {
    id: "12",
    name: "Cheesecake",
    price: 12,
    category: "Desserts",
    description: "Creamy cheesecake with a graham cracker crust",
  },
  {
    id: "13",
    name: "Apple Pie",
    price: 11,
    category: "Desserts",
    description: "Classic apple pie with a flaky crust and cinnamon-spiced filling",
  },
  {
    id: "14",
    name: "Brownie",
    price: 9,
    category: "Desserts",
    description: "Rich chocolate brownie served with a scoop of vanilla ice cream",
  },
]
